### ISSUE TITLE
Add 3rd party API keys to the configuration file

### ISSUE THREAD

**Issue by MadBomber** [MadBomber/sqa#4]
Add a new section to the config file.

```yml
api_keys:
  - alpha_vantage: xyzzy
  - trading_view: xyzzy
```

and/or setup ERB on the config file:

```yml
api_keys:
  - alpha_vantage:<%= ENV['AV_API_KEY'] %>
  - trading_view: <%= ENV['TV_API_KEY'] %>
```

May have to add CLI options "--alpha_vantage xyzzy --trading_view xyzzy"

what should "xyzzy" be the actual value of the API key or the environment variable name that holds the value.  I'm leaning toward the envar name.

The advantage is that the envar name can be whatever the user likes or is using in some pre-existing applications.
